In [1]:
Pandas Series

SyntaxError: invalid syntax (2636366476.py, line 1)

In [2]:
import numpy  as np
import pandas as pd

In [5]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
done

In [ ]:
DATA FRAMES

In [10]:
import numpy as np
import pandas as pd

In [11]:
data ={
    'Name': ['John','Anna','Peter','Linda'],
    'Age': [28,34,29,42],
    'City': ['New york', 'paris' , 'berlin','london'],
    'Salary': [65000,70000,62000,85000]
}
df = pd.DataFrame(data)

In [13]:
df

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     paris   70000
2  Peter   29    berlin   62000
3  Linda   42    london   85000

In [14]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [16]:
df[['Name','Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [17]:
df["Designation"] =['doct','eng','tech','bus']

In [18]:
df

    Name  Age      City  Salary Designation
0   John   28  New york   65000        doct
1   Anna   34     paris   70000         eng
2  Peter   29    berlin   62000        tech
3  Linda   42    london   85000         bus

In [20]:
df.drop('Designation',axis = 1)

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     paris   70000
2  Peter   29    berlin   62000
3  Linda   42    london   85000

In [21]:
df

    Name  Age      City  Salary Designation
0   John   28  New york   65000        doct
1   Anna   34     paris   70000         eng
2  Peter   29    berlin   62000        tech
3  Linda   42    london   85000         bus

In [22]:
df.drop('Designation',axis = 1,inplace =True)

In [23]:
df

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     paris   70000
2  Peter   29    berlin   62000
3  Linda   42    london   85000

In [26]:
df.loc[0]

Name          John
Age             28
City      New york
Salary       65000
Name: 0, dtype: object

In [27]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New york   65000
1  Anna   34     paris   70000

In [28]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New york   65000
1     paris   70000

In [29]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [ ]:
conditional

In [30]:
df[df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   paris   70000
3  Linda   42  london   85000

In [36]:
df[(df['Age']> 30) & (df['City'] == 'paris')]

   Name  Age   City  Salary
1  Anna   34  paris   70000

In [ ]:
done

In [37]:
Missing data

SyntaxError: invalid syntax (3196666677.py, line 1)

In [38]:
import numpy as np
import pandas as pd

In [49]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [45]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [46]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [47]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [48]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [50]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [52]:
df.dropna(thresh =3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [53]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [54]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [56]:
values = {'A':0,'B':20,'C':30,'D':40}
df.fillna(value=values)

     A  B     C     D
0  1.0  1   1.0   1.0
1  2.0  2   2.0  40.0
2  0.0  3   3.0  40.0
3  4.0  4  30.0  40.0
4  5.0  5  30.0   5.0

In [ ]:
Merging-Joining-Concatination

In [57]:
import numpy as np
import pandas as pd

In [58]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [59]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [60]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [64]:
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [65]:
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [66]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [67]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [68]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [69]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [70]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [71]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [72]:
pd.concat([df1,df2],axis =1 )

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [75]:
**joining**

SyntaxError: invalid syntax (2410262069.py, line 1)

In [76]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [77]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [78]:
df2

   score
2     85
3     90
4     75

In [79]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [80]:
df1.join(df2,how = 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [81]:
** Group By Aggregation **

SyntaxError: invalid syntax (2036383640.py, line 1)

In [2]:
import numpy as np 
import pandas as pd

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [84]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [87]:
cat = df.groupby('Category')
cat
for i, v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [88]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [91]:
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [95]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [96]:
*Aggregation*

SyntaxError: invalid syntax (3182804695.py, line 1)

In [97]:
df['Sales'].mean()

np.float64(187.5)

In [98]:
df['Sales'].min()

np.int64(100)

In [99]:
df['Sales'].max()

np.int64(300)

In [100]:
df['Sales'].count()

np.int64(8)

In [101]:
df['Sales'].std()

np.float64(66.06274074155351)

In [102]:
df['Sales'].median()

np.float64(190.0)

In [103]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [105]:
df['Sales'].agg(['mean','min','max','median'])

mean      187.5
min       100.0
max       300.0
median    190.0
Name: Sales, dtype: float64

In [106]:
**Pivot tables

SyntaxError: invalid syntax (3534177148.py, line 1)

In [2]:
import numpy as np 
import pandas as pd

In [4]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}


df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    493     93   John  January      Q1
1  2023-01-02       B   West    295     96   Mary  January      Q1
2  2023-01-03       C  North    176     65    Bob  January      Q1
3  2023-01-04       D  South    700     20  Alice  January      Q1
4  2023-01-05       A   East    427     26   John  January      Q1
5  2023-01-06       B   West    553     30   Mary  January      Q1
6  2023-01-07       C  North    907     58    Bob  January      Q1
7  2023-01-08       D  South    252     66  Alice  January      Q1
8  2023-01-09       A   East    905     71   John  January      Q1
9  2023-01-10       B   West    329     49   Mary  January      Q1
10 2023-01-11       C  North    164     60    Bob  January      Q1
11 2023-01-12       D  South    125     90  Alice  January      Q1
12 2023-01-13       A   East    477     75   John  January      Q1
13 2023-01-14       B   West    805     25   Mary  January      Q1
14 2023-01-15       C  North    538     74    Bob  January      Q1
15 2023-01-16       D  South    618     47  Alice  January      Q1
16 2023-01-17       A   East    784     23   John  January      Q1
17 2023-01-18       B   West    295     18   Mary  January      Q1
18 2023-01-19       C  North    657     95    Bob  January      Q1
19 2023-01-20       D  South    466     42  Alice  January      Q1

In [8]:
pd.pivot_table(df,values = 'Sales', index= 'Region', columns = 'Product',aggfunc = 'median')

Product      A      B      C      D
Region
East     492.0    NaN    NaN    NaN
North      NaN    NaN  521.0    NaN
South      NaN    NaN    NaN  762.0
West       NaN  612.0    NaN    NaN

In [12]:
pivot2 = pd.pivot_table(df,values = ['Sales','Units'], index= 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     604.2    NaN    NaN    NaN  50.4   NaN   NaN   NaN
North      NaN    NaN  635.0    NaN   NaN   NaN  53.6   NaN
South      NaN    NaN    NaN  655.6   NaN   NaN   NaN  51.2
West       NaN  637.4    NaN    NaN   NaN  61.4   NaN   NaN

In [6]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [ ]:
DONE

In [ ]:
OPerations

In [7]:
import numpy as np 
import pandas as pd

In [8]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [9]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [10]:
df1.shape

(5, 3)

#

In [11]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [12]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [13]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [15]:
 df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
appling func

In [16]:
def square(x):
    return x==2

df

In [19]:
df1['D'] = df1["B"].apply(square)

In [21]:
df1

   A   B    C      D
0  1  10  100  False
1  2  20  200  False
2  3  30  300  False
3  4  40  400  False
4  5  50  500  False